### ISSUE TITLE
[Ente®]

### ISSUE THREAD

**Issue by gdamiaN538** [MicrosoftDocs/entra-docs#231]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 23b434db-9091-da08-2c96-839d462bc114
* Version Independent ID: 7bee76e7-acdc-5bc5-50ec-6004c73b9a95
* Content: [Quickstart: Register and expose a web API - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/quickstart-configure-app-expose-web-apis)
* Content Source: [docs/identity-platform/quickstart-configure-app-expose-web-apis.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/quickstart-configure-app-expose-web-apis.md)
* Service: **active-directory**
* Sub-service: **develop**
* GitHub Login: @cilwerner
* Microsoft Alias: **cwerner**
```[tasklist]
### Tasks
- [ ] https://github.com/MicrosoftDocs/entra-docs/issues/227
```

```[tasklist]
### Tasks
- [ ] https://github.com/MicrosoftDocs/entra-docs/issues/209
- [ ] https://github.com/MicrosoftDocs/entra-docs/issues/227
```

```[tasklist]
### Tasks
- [ ] https://github.com/MicrosoftDocs/entra-docs/issues/229
- [ ] https://github.com/MicrosoftDocs/entra-docs/issues/228
- [ ] https://github.com/MicrosoftDocs/entra-docs/issues/230
```

**Comment by gdamiaN538** [comment]
Editions*

**Comment by AjayBathini-MSFT** [comment]
@gdamiaN538 
Could you please elaborate the query for better understanding. So, we can assist you further.
